{
  "openapi": "3.0.2",
  "info": {
    "title": "Get There Logistics API",
    "version": "1.1.9",
    "description": "The Get There Logistics API is organized around REST. Our API has predictable resource-oriented URLs, accepts form-encoded request bodies, returns JSON-encoded responses, and uses standard HTTP response codes, authentication, and verbs.",
    "termsOfService": "",
    "contact": {
      "name": "Get There Jamaica",
      "url": "https://www.getthereja.com",
      "email": "getthere@jamaker.com"
    },
    "x-logo": {
      "url": "https://s3.amazonaws.com/jamaker/dev/fileFolder/Ehjih3fxE6goTuL7f/3trEgLrGKW6zPo5R6.png"
    }
  },
  "servers": [
    {
      "url": "https://www.getthereja.com/api",
      "description": "All calls must be made using \"https\", with an accompanying api_key + api_secret hash.",
      "x-last-modified": 1616554197103
    }
  ],
  "paths": {
    "/gtthr_v1_calculateJob": {
      "summary": "Calculate Job - Calculate the cost of a new job which is to be dispatched.",
      "description": "Get the cost of a job by sending the key destination points. This request returns a job_id, which will be required to submit that job.",
      "post": {
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/gtthr_calculateJob"
              },
              "examples": {
                "example-1": {
                  "value": {
                    "serviceType": "Delivery",
                    "addressFrom": {
                      "fullName": "Christopher Gayle",
                      "emailAddress": "getthere@jamaker.com",
                      "phoneNumber": "8767777777",
                      "streetAddress": "15 Ring Rd, Kingston, Jamaica",
                      "latitude": 18.006115,
                      "longitude": -76.745711
                    },
                    "addressMiddle": [
                      {
                        "fullName": "Christopher Gayle",
                        "emailAddress": "getthere@jamaker.com",
                        "phoneNumber": "8767777777",
                        "streetAddress": "Opposite Red Hills Mall, Kingston, Jamaica",
                        "latitude": 18.034345,
                        "longitude": -76.811481
                      }
                    ],
                    "addressTo": {
                      "fullName": "Christopher Gayle",
                      "emailAddress": "getthere@jamaker.com",
                      "phoneNumber": "8767777777",
                      "streetAddress": "Torver Cr, Portmore, Jamaica",
                      "latitude": 17.974324,
                      "longitude": -76.884313
                    }
                  }
                }
              }
            }
          },
          "required": true,
          "description": ""
        },
        "tags": [
          "Jobs"
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "description": "",
                  "type": "object",
                  "properties": {
                    "job_id": {
                      "type": "string",
                      "description": "job_id is to be preserved in order to submit the job if cost is accepted, track it and / or cancel it."
                    },
                    "distance": {
                      "type": "number",
                      "description": "Distance of journey in km."
                    },
                    "duration": {
                      "type": "number",
                      "description": "Estimated duration of journey in minutes."
                    },
                    "cost": {
                      "type": "number",
                      "description": "Final cost of job order, which will be charged to the account's card saved in your payment methods once the /gtthr_v1_submitJob instruction is sent with matching job_id."
                    },
                    "currency": {
                      "type": "string",
                      "description": "Currency of the cost of job order."
                    }
                  }
                },
                "example": {
                  "status": "success",
                  "job_id": "oQGjrQ2JfjzmynLaE",
                  "distance": 7,
                  "duration": 5,
                  "cost": 500,
                  "currency": "JMD"
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "job_id": "oQGjrQ2JfjzmynLaE",
                      "distance": 7,
                      "duration": 5,
                      "cost": 500,
                      "currency": "JMD"
                    }
                  }
                }
              }
            },
            "description": "Operation succeeded.",
            "x-last-modified": 1616538429127,
            "headers": {},
            "links": {}
          }
        },
        "operationId": "/gtthr_v1_calculateJob",
        "summary": "Calculate Job - /gtthr_v1_calculateJob (Step 1)",
        "description": "Calculate the cost of a new job which is to be dispatched. By sending the required information, a job will enter the dispatching system and operators are contacted accordingly.\n\nThis function comes at a cost as accurate routes are plotted to acquire a clear route, duration and distance. You will be charged US$3.00 for every 1000 jobs calculated. Effectively this function costs US$0.003 / calculated job.",
        "externalDocs": {
          "url": ""
        }
      },
      "x-last-modified": 1616543121327
    },
    "/gtthr_v1_submitJob": {
      "summary": "Submit Job - Submit a job into the active job queue for operators to action.",
      "description": "Using the job_id retrieved from a successful call to /gtthr_v1_calculateJob, use this submit command to enter it into the dispatching queue so operators may be contacted accordingly.",
      "post": {
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/gtthr_job_id"
              }
            }
          },
          "required": true,
          "description": ""
        },
        "tags": [
          "Jobs"
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "description": "",
                  "type": "object",
                  "properties": {
                    "response": {
                      "type": "string",
                      "description": "\"success\" is returned as a response"
                    },
                    "job_id": {
                      "type": "string",
                      "description": "The same job_id of the request is returned"
                    }
                  }
                },
                "example": {
                  "status": "success",
                  "job_id": "oQGjrQ2JfjzmynLaE"
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "response": "success",
                      "job_id": "oQGjrQ2JfjzmynLaE"
                    }
                  }
                }
              },
              "application/xml": {
                "schema": {
                  "description": "",
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "minLength": 1
                    },
                    "job_id": {
                      "type": "string",
                      "minLength": 1
                    }
                  },
                  "required": [
                    "status",
                    "job_id"
                  ]
                }
              }
            },
            "description": "Operation succeeded.",
            "x-last-modified": 1616538429127
          }
        },
        "operationId": "/gtthr_v1_submitJob",
        "summary": "Submit Job - /gtthr_v1_submitJob (Step 2)",
        "description": "Submit a calculated job into the active job queue for operators to action. Using the job_id retrieved from a successful call to /gtthr_v1_calculateJob, use this submit command to enter it into the dispatching queue so operators may be contacted accordingly.\n\nA payment method MUST be added in order to submit a job. The card you have saved will be charged for the trip that is being dispatched, so please ensure you have collected from your customer already.",
        "externalDocs": {
          "url": ""
        }
      },
      "x-last-modified": 1616542883949
    },
    "/gtthr_v1_trackJob": {
      "summary": "Track Job - Get the status of an existing job in the queue.",
      "description": "Using the job_id, you may retrieve the current status of the job, which also returns the operator's current location.",
      "post": {
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/gtthr_job_id"
              }
            }
          },
          "required": true,
          "description": ""
        },
        "tags": [
          "Jobs"
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "description": "",
                  "type": "object",
                  "properties": {
                    "currentJobStatus": {
                      "type": "string",
                      "description": "The job's current status, which may be \"Pending\", \"Requested\", \"Accepted\", \"On The Way\", \"Traveling\", \"Complete\" or \"Cancelled\""
                    },
                    "operatorFullname": {
                      "type": "string",
                      "description": "Fullname of the individual carrying out the job order."
                    },
                    "operatorPhonenumber": {
                      "type": "string",
                      "description": "Phone number of the operator carrying out the job order."
                    },
                    "operatorLocation": {
                      "type": "object",
                      "description": "The GPS coordinates of the operator carrying out the job order.",
                      "properties": {
                        "latitude": {
                          "type": "number"
                        },
                        "longitude": {
                          "type": "number"
                        }
                      }
                    }
                  }
                },
                "example": {
                  "status": "success",
                  "job_id": "oQGjrQ2JfjzmynLaE",
                  "currentStatus": "On The Way",
                  "operatorFullname": "Christopher Gayle",
                  "operatorPhonenumber": "8767777777",
                  "operatorLocation": {
                    "latitude": 18.034345,
                    "longitude": -76.811481
                  }
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "job_id": "oQGjrQ2JfjzmynLaE",
                      "currentJobStatus": "On The Way",
                      "operatorFullname": "Christopher Gayle",
                      "operatorPhonenumber": "8767777777",
                      "operatorLocation": {
                        "latitude": 18.034345,
                        "longitude": -76.811481
                      }
                    }
                  }
                }
              }
            },
            "description": "Operation succeeded.",
            "x-last-modified": 1616538429127
          }
        },
        "operationId": "/gtthr_v1_trackJob",
        "summary": "Track Job - /gtthr_v1_trackJob (Step 3)",
        "description": "Get the status of an existing job in the queue. Using the job_id, you may retrieve the current status of the job, which also returns the operator's current location.",
        "externalDocs": {
          "url": ""
        }
      },
      "x-last-modified": 1616542916346
    },
    "/gtthr_v1_cancelJob": {
      "summary": "Cancel Job - Cancel an existing job in the queue.",
      "description": "Using the job_id, you may cancel a job which has been previously dispatched.",
      "post": {
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/gtthr_job_id"
              }
            }
          },
          "required": true,
          "description": ""
        },
        "tags": [
          "Jobs"
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "description": "",
                  "type": "object",
                  "properties": {
                    "response": {
                      "type": "string",
                      "description": "\"success\" is returned as a response"
                    },
                    "job_id": {
                      "type": "string",
                      "description": "The same job_id of the request is returned"
                    }
                  }
                },
                "example": {
                  "status": "success",
                  "job_id": "oQGjrQ2JfjzmynLaE"
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "response": "success",
                      "job_id": "oQGjrQ2JfjzmynLaE"
                    }
                  }
                }
              }
            },
            "description": "Operation succeeded.",
            "x-last-modified": 1616544140021
          }
        },
        "operationId": "/gtthr_v1_cancelJob",
        "summary": "Cancel Job - /gtthr_v1_cancelJob",
        "description": "Cancel an existing job in the queue. Using the job_id, you may cancel a job which has been previously dispatched.\n\nIf this job has been submitted already, and a charge to your card made. That charge will be reversed immediately to return those funds to your account.",
        "externalDocs": {
          "url": ""
        }
      },
      "x-last-modified": 1616543314980
    },
    "/gtthr_v1_submitOperator": {
      "post": {
        "summary": "Submit Operator - /gtthr_v1_submitOperator",
        "operationId": "post-gtthr_v1_submitOperator",
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "description": "",
                  "type": "object",
                  "properties": {
                    "response": {
                      "type": "string",
                      "minLength": 1,
                      "description": "\"success\" is returned as a response"
                    }
                  }
                },
                "example": {
                  "status": "success",
                  "job_id": "oQGjrQ2JfjzmynLaE"
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "response": "success"
                    }
                  }
                }
              }
            },
            "description": "Operation succeeded.",
            "x-last-modified": 1616544140021
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/gtthr_operator"
              },
              "examples": {
                "example-1": {
                  "value": {
                    "firstName": "string",
                    "lastName": "string",
                    "emailAddress": "string",
                    "phoneNumber": "string",
                    "type": "string",
                    "vehicle": {
                      "licensePlateNumber": "string",
                      "make": "string",
                      "model": "string",
                      "colour": "string",
                      "bodyType": "string",
                      "seatCount": 0,
                      "registrationExpiryDate": "string",
                      "fitnessExpiryDate": "string",
                      "insuranceExpiryDate": "string"
                    },
                    "bankAccount": {
                      "nameOnAccount": "string",
                      "accountNumber": "string",
                      "accountType": "string",
                      "code": "string",
                      "branchCode": "string"
                    },
                    "pictures": {
                      "selfie": [
                        "https://s3.amazonaws.com/jamaker/dev/fileFolder/Ehjih3fxE6goTuL7f/3trEgLrGKW6zPo5R6.png"
                      ],
                      "vehicle": [
                        "https://s3.amazonaws.com/jamaker/dev/fileFolder/Ehjih3fxE6goTuL7f/3trEgLrGKW6zPo5R6.png"
                      ],
                      "driversLicense": [
                        "https://s3.amazonaws.com/jamaker/dev/fileFolder/Ehjih3fxE6goTuL7f/3trEgLrGKW6zPo5R6.png"
                      ],
                      "vehicleFitness": [
                        "https://s3.amazonaws.com/jamaker/dev/fileFolder/Ehjih3fxE6goTuL7f/3trEgLrGKW6zPo5R6.png"
                      ],
                      "vehicleInsurance": [
                        "https://s3.amazonaws.com/jamaker/dev/fileFolder/Ehjih3fxE6goTuL7f/3trEgLrGKW6zPo5R6.png"
                      ],
                      "vehicleRegistration": [
                        "https://s3.amazonaws.com/jamaker/dev/fileFolder/Ehjih3fxE6goTuL7f/3trEgLrGKW6zPo5R6.png"
                      ],
                      "vehiclePPV": [
                        "https://s3.amazonaws.com/jamaker/dev/fileFolder/Ehjih3fxE6goTuL7f/3trEgLrGKW6zPo5R6.png"
                      ]
                    }
                  }
                }
              }
            },
            "application/javascript": {
              "schema": {
                "type": "object",
                "properties": {}
              }
            }
          },
          "description": ""
        },
        "tags": [
          "Operators"
        ],
        "description": "Add a courier to the logistics network. By sending the required information, an operator will be created allowing such a person to log into the logistics network and participate in the fulfillment operations."
      }
    }
  },
  "components": {
    "schemas": {
      "gtthr_calculateJob": {
        "type": "object",
        "example": {
          "serviceType": "Delivery",
          "addressFrom": {
            "fullName": "Christopher Gayle",
            "emailAddress": "getthere@jamaker.com",
            "phoneNumber": "8767777777",
            "streetAddress": "15 Ring Rd, Kingston, Jamaica",
            "latitude": 18.006115,
            "longitude": -76.745711
          },
          "addressMiddle": [
            {
              "fullName": "Christopher Gayle",
              "emailAddress": "getthere@jamaker.com",
              "phoneNumber": "8767777777",
              "streetAddress": "Opposite Red Hills Mall, Kingston, Jamaica",
              "latitude": 18.034345,
              "longitude": -76.811481
            }
          ],
          "addressTo": {
            "fullName": "Christopher Gayle",
            "emailAddress": "getthere@jamaker.com",
            "phoneNumber": "8767777777",
            "streetAddress": "Torver Cr, Portmore, Jamaica",
            "latitude": 17.974324,
            "longitude": -76.884313
          }
        },
        "x-last-modified": 1616543948900,
        "x-examples": {
          "example-1": {
            "serviceType": "Delivery",
            "addressFrom": {
              "fullName": "Christopher Gayle",
              "emailAddress": "getthere@jamaker.com",
              "phoneNumber": "8767777777",
              "streetAddress": "15 Ring Rd, Kingston, Jamaica",
              "latitude": 18.006115,
              "longitude": -76.745711
            },
            "addressMiddle": [
              {
                "fullName": "Christopher Gayle",
                "emailAddress": "getthere@jamaker.com",
                "phoneNumber": "8767777777",
                "streetAddress": "Opposite Red Hills Mall, Kingston, Jamaica",
                "latitude": 18.034345,
                "longitude": -76.811481
              }
            ],
            "addressTo": {
              "fullName": "Christopher Gayle",
              "emailAddress": "getthere@jamaker.com",
              "phoneNumber": "8767777777",
              "streetAddress": "Torver Cr, Portmore, Jamaica",
              "latitude": 17.974324,
              "longitude": -76.884313
            }
          }
        },
        "title": "",
        "description": "",
        "properties": {
          "serviceType": {
            "type": "string",
            "minLength": 1,
            "description": "\"Fast Food\", \"Frozen Food\", \"Grocery\", or \"Small Package\""
          },
          "addressFrom": {
            "type": "object",
            "minProperties": 2,
            "description": "Location from which the package will be collected by the courier, or person/s picked up.",
            "required": [
              "fullName",
              "emailAddress",
              "phoneNumber",
              "streetAddress",
              "latitude",
              "longitude"
            ],
            "properties": {
              "fullName": {
                "type": "string",
                "description": "Fullname of person expecting operator / package."
              },
              "emailAddress": {
                "type": "string",
                "description": "Email address of person expecting operator / package."
              },
              "phoneNumber": {
                "type": "string",
                "description": "Phone number of person expecting operator / package."
              },
              "streetAddress": {
                "type": "string",
                "description": "Human readable street address to be broadcasted to all available nearby couriers."
              },
              "latitude": {
                "type": "number"
              },
              "longitude": {
                "type": "number"
              }
            }
          },
          "addressMiddle": {
            "type": "array",
            "description": "Location/s at which the taxi / bus will stop along it's route to the final destination. (Not to be used for package delivery)",
            "items": {
              "type": "object",
              "properties": {
                "fullName": {
                  "type": "string",
                  "description": "Fullname of person expecting operator / package."
                },
                "emailAddress": {
                  "type": "string",
                  "description": "Email address of person expecting operator / package."
                },
                "phoneNumber": {
                  "type": "string",
                  "description": "Phone number of person expecting operator / package."
                },
                "streetAddress": {
                  "type": "string",
                  "description": "Human readable street address to be broadcasted to all available nearby couriers."
                },
                "latitude": {
                  "type": "number"
                },
                "longitude": {
                  "type": "number"
                }
              },
              "required": [
                "fullName",
                "emailAddress",
                "phoneNumber",
                "streetAddress",
                "latitude",
                "longitude"
              ]
            }
          },
          "addressTo": {
            "type": "object",
            "minProperties": 2,
            "description": "Location to which the package will be delivered by the courier, or person/s dropped off.",
            "required": [
              "fullName",
              "emailAddress",
              "phoneNumber",
              "streetAddress",
              "latitude",
              "longitude"
            ],
            "properties": {
              "fullName": {
                "type": "string",
                "description": "Fullname of person expecting operator / package."
              },
              "emailAddress": {
                "type": "string",
                "description": "Email address of person expecting operator / package."
              },
              "phoneNumber": {
                "type": "string",
                "description": "Phone number of person expecting operator / package."
              },
              "streetAddress": {
                "type": "string",
                "description": "Human readable street address to be broadcasted to all available nearby couriers."
              },
              "latitude": {
                "type": "number"
              },
              "longitude": {
                "type": "number"
              }
            }
          }
        },
        "required": [
          "serviceType",
          "addressFrom",
          "addressTo"
        ]
      },
      "gtthr_job_id": {
        "type": "object",
        "example": {
          "job_id": "oQGjrQ2JfjzmynLaE"
        },
        "x-last-modified": 1616543983887,
        "properties": {
          "job_id": {
            "type": "string",
            "minLength": 1,
            "description": "The job_id is returned in the initial /gtthr_v1_calculateJob step, save it and use it here to perform this action."
          }
        },
        "required": [
          "job_id"
        ]
      },
      "gtthr_operator": {
        "description": "",
        "type": "object",
        "x-examples": {
          "example-1": {
            "firstName": "string",
            "lastName": "string",
            "emailAddress": "string",
            "phoneNumber": "string",
            "type": "string",
            "vehicle": {
              "licensePlateNumber": "string",
              "make": "string",
              "model": "string",
              "colour": "string",
              "bodyType": "string",
              "seatCount": 0,
              "registrationExpiryDate": "string",
              "fitnessExpiryDate": "string",
              "insuranceExpiryDate": "string"
            },
            "bankAccount": {
              "nameOnAccount": "string",
              "accountNumber": "string",
              "accountType": "string",
              "code": "string",
              "branchCode": "string"
            },
            "pictures": {
              "selfie": [
                "https://s3.amazonaws.com/jamaker/dev/fileFolder/Ehjih3fxE6goTuL7f/3trEgLrGKW6zPo5R6.png"
              ],
              "vehicle": [
                "https://s3.amazonaws.com/jamaker/dev/fileFolder/Ehjih3fxE6goTuL7f/3trEgLrGKW6zPo5R6.png"
              ],
              "driversLicense": [
                "https://s3.amazonaws.com/jamaker/dev/fileFolder/Ehjih3fxE6goTuL7f/3trEgLrGKW6zPo5R6.png"
              ],
              "vehicleFitness": [
                "https://s3.amazonaws.com/jamaker/dev/fileFolder/Ehjih3fxE6goTuL7f/3trEgLrGKW6zPo5R6.png"
              ],
              "vehicleInsurance": [
                "https://s3.amazonaws.com/jamaker/dev/fileFolder/Ehjih3fxE6goTuL7f/3trEgLrGKW6zPo5R6.png"
              ],
              "vehicleRegistration": [
                "https://s3.amazonaws.com/jamaker/dev/fileFolder/Ehjih3fxE6goTuL7f/3trEgLrGKW6zPo5R6.png"
              ],
              "vehiclePPV": [
                "https://s3.amazonaws.com/jamaker/dev/fileFolder/Ehjih3fxE6goTuL7f/3trEgLrGKW6zPo5R6.png"
              ]
            }
          }
        },
        "properties": {
          "firstName": {
            "type": "string",
            "minLength": 1,
            "description": "Firstname of operator."
          },
          "lastName": {
            "type": "string",
            "minLength": 1,
            "description": "Lastname of operator."
          },
          "emailAddress": {
            "type": "string",
            "minLength": 1,
            "description": "Email address of operator. Which must be accurate to ensure that the operator has proper access when they login to the logistics portal."
          },
          "phoneNumber": {
            "type": "string",
            "minLength": 1,
            "description": "Phone number of operator."
          },
          "type": {
            "type": "string",
            "minLength": 1,
            "description": "\"Car\" or \"Motorcycle\""
          },
          "vehicle": {
            "type": "object",
            "required": [
              "licensePlateNumber",
              "make",
              "model",
              "colour",
              "bodyType",
              "seatCount",
              "registrationExpiryDate",
              "fitnessExpiryDate",
              "insuranceExpiryDate"
            ],
            "description": "Details about the vehicle the operator will be utilizing as they go about fulfilling job orders. Some of this information is shown to recipients / travelers that are tracking the order.",
            "properties": {
              "licensePlateNumber": {
                "type": "string",
                "minLength": 1
              },
              "make": {
                "type": "string",
                "minLength": 1
              },
              "model": {
                "type": "string",
                "minLength": 1
              },
              "colour": {
                "type": "string",
                "minLength": 1
              },
              "bodyType": {
                "type": "string",
                "minLength": 1
              },
              "seatCount": {
                "type": "number"
              },
              "registrationExpiryDate": {
                "type": "string",
                "minLength": 1
              },
              "fitnessExpiryDate": {
                "type": "string",
                "minLength": 1
              },
              "insuranceExpiryDate": {
                "type": "string",
                "minLength": 1
              }
            }
          },
          "bankAccount": {
            "type": "object",
            "required": [
              "nameOnAccount",
              "accountNumber",
              "accountType",
              "code",
              "branchCode"
            ],
            "description": "The bank account details of the operator that the platform will direct funds to once they have completed a job.",
            "properties": {
              "nameOnAccount": {
                "type": "string",
                "minLength": 1
              },
              "accountNumber": {
                "type": "string",
                "minLength": 1
              },
              "accountType": {
                "type": "string",
                "minLength": 1
              },
              "code": {
                "type": "string",
                "minLength": 1
              },
              "branchCode": {
                "type": "string",
                "minLength": 1
              }
            }
          },
          "pictures": {
            "type": "object",
            "description": "Pictures of the operator, their vehicle and associated documents required for legal operations on the road.",
            "properties": {
              "selfie": {
                "type": "array",
                "description": "Pictures of the operator themself. These images are made available to travelers / recipients when tracking a job destined to / for them.",
                "items": {
                  "type": "string"
                }
              },
              "vehicle": {
                "type": "array",
                "description": "Pictures of the operator's vehicle. These images are made available to travelers / recipients when tracking a job destined to / for them.",
                "items": {
                  "type": "string"
                }
              },
              "driversLicense": {
                "type": "array",
                "description": "Pictures of the operator's driver's license. These images are collected for security purposes, and will not be displayed to the average recipient / traveler.",
                "items": {
                  "type": "string"
                }
              },
              "vehicleFitness": {
                "type": "array",
                "description": "Pictures of the operator's vehicle fitness. These images are collected for security purposes, and will not be displayed to the average recipient / traveler.",
                "items": {
                  "type": "string"
                }
              },
              "vehicleInsurance": {
                "type": "array",
                "description": "Pictures of the operator's vehicle insurance documents. These images are collected for security purposes, and will not be displayed to the average recipient / traveler.",
                "items": {
                  "type": "string"
                }
              },
              "vehicleRegistration": {
                "type": "array",
                "description": "Pictures of the operator's vehicle registration. These images are collected for security purposes, and will not be displayed to the average recipient / traveler.",
                "items": {
                  "type": "string"
                }
              },
              "vehiclePPV": {
                "type": "array",
                "description": "Pictures of the operator's PPV license. These images are collected for security purposes, and will not be displayed to the average recipient / traveler.",
                "items": {
                  "type": "string"
                }
              }
            }
          }
        },
        "required": [
          "firstName",
          "lastName",
          "emailAddress",
          "phoneNumber",
          "type",
          "vehicle",
          "bankAccount"
        ]
      }
    },
    "responses": {
      "200": {
        "description": "Operation success.",
        "content": {
          "application/json": {
            "schema": {
              "type": "object"
            }
          }
        }
      }
    },
    "securitySchemes": {
      "API Key": {
        "type": "apiKey",
        "description": "Depending on your preferred courier service, you will need to register on their website to acquire an authentic api_key and api_secret pair. \n\nYou may find your api_key in your account settings. This key never changes and should be kept private.",
        "name": "api_key",
        "in": "query",
        "x-last-modified": 1616521511409
      },
      "API Secret Hash": {
        "type": "apiKey",
        "description": "You may find your api_secret in your account settings. This secret may be changed via your settings, but if changed your systems must communicate with the new key or lose their connection altogether.\n\nUse HMAC-SHA1 to create a hash using (api_key,api_secret) and send in the header of all your requests.",
        "name": "api_secret",
        "in": "query",
        "x-last-modified": 1616568112620
      }
    },
    "headers": {},
    "parameters": {}
  },
  "tags": [
    {
      "name": "Jobs",
      "description": "Dispatching job orders to couriers our taxi operators are at the center of this platforms purpose. Using this API you may create jobs, check their status or otherwise cancel outstanding job orders. Please see the available commands bellow.",
      "externalDocs": {
        "description": "",
        "url": ""
      },
      "x-last-modified": 1616544916101
    },
    {
      "name": "Operators",
      "description": "Operators are able to view jobs in the queue, accept them, automatically report accurate proximity during fulfillment and update the status of jobs they have accepted.",
      "x-last-modified": 1616682025782
    }
  ],
  "security": []
}